# Generated by Django 5.2.6 on 2025-09-15 19:04

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KitConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dormitorios', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0)),
                ('categorias', models.ManyToManyField(related_name='kits', to='store.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaneleSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_obs', models.CharField(blank=True, max_length=100, null=True)),
                ('madera_union', models.CharField(blank=True, max_length=100, null=True)),
                ('espesor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorias', models.ManyToManyField(related_name='paneles', to='store.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='imagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=store.models.ruta_imagen)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='store.kitconstruccion')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='store.panelesip')),
            ],
        ),
    ]
