# Generated by Django 5.2.6 on 2025-10-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0003_remove_kitconstruccion_slug_remove_panelsip_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('disponible', models.PositiveIntegerField(default=0)),
                ('reservado', models.PositiveIntegerField(default=0)),
                ('modo_stock', models.CharField(choices=[('stock', 'Con stock'), ('pedido', 'Por pedido')], default='pedido', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
