# Generated by Django 5.2.6 on 2025-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='metodo_pago',
            field=models.CharField(choices=[('pago_tienda', 'Pago en Tienda'), ('pago_web', 'Pago Web')], default='pago_tienda', max_length=20),
        ),
    ]
