# Generated by Django 5.2.6 on 2025-10-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_detallepedido_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('pago_tienda', 'Pago en Tienda'), ('pago_web', 'Pago Web')], default='pago_tienda', max_length=20),
        ),
    ]
