# Generated by Django 5.2.6 on 2025-10-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_detallepedido_metodo_pago_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='producto_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
