# Generated by Django 5.2.6 on 2025-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_detallepedido_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto_id',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
