# Generated by Django 5.2.6 on 2025-10-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_remove_detallepedido_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('pago_tienda', 'Pago en Tienda'), ('pago_web', 'Pago Web')], default='Pago en Tienda', max_length=20),
        ),
    ]
