# Generated by Django 5.2.6 on 2025-10-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('control', '0005_remove_detallepedido_producto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_producto',
            field=models.CharField(default='Producto eliminado', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='tipo',
            field=models.CharField(default='desconocido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='control.local'),
        ),
    ]
