# Generated by Django 5.2.6 on 2025-10-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_pedido_estado_alter_pedido_metodo_pago'),
        ('control', '0006_detallepedido_nombre_producto_detallepedido_tipo_and_more'),
    ]

    operations = [
    ]
