# Generated by Django 5.2.6 on 2025-10-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_merge_20251012_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('pago_tienda', 'Pago en Tienda'), ('pago_web', 'Pago Web')], default='pago_tienda', max_length=20),
        ),
    ]
