# Generated by Django 5.2.6 on 2025-10-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_pedido_estado_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_unitario',
        ),
    ]
