# Generated by Django 5.2.6 on 2025-09-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_kitconstruccion_slug_panelsip_slug_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitconstruccion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='panelsip',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
