# Generated by Django 5.2.6 on 2025-11-14 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('texto', models.TextField()),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
