# Generated by Django 5.2.6 on 2025-11-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
